config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :portals
   resources :portals do
    resources :comments
  end

devise_for :users, :controllers => { registrations: 'registrations' }

  get '/users/:id', to: 'users#show'

  root 'portals#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :portal

  validates :body, presence: true, allow_blank: false
end

app/models/portal.rb
class Portal < ApplicationRecord
	belongs_to :user 
	has_many :comments, :dependent => :delete_all
	has_many :taggings, :dependent => :delete_all
	has_many :tags, through: :taggings, :dependent => :delete_all
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :posts, through: :taggings

	def assigned(portal)
    	portal.taggings.where(tag_id: self.id).any?
  	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :portal
end

app/models/user.rb
class User < ApplicationRecord
	  mount_uploader :avatars, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  


  has_many :portals
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @portal = Portal.find(params[:portal_id])
    @comment = @portal.comments.create(comment_params)
    redirect_to portal_path(@portal)
  end

  def show
  end 

  def destroy
  @portal = Portal.find(params[:portal_id])
  @comment = @portal.comments.find(params[:id])
  @comment.destroy

  redirect_to portal_path(@portal)
end

  private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :in_character)
  end
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  def index
  	@user = current_user.id
  	@portals = Portal.all 
  end
  def show
    @portal = Portal.find(params[:id])
    @comment = Comment.new 
    @comments = @portal.comments
  end
  def new 
  	@portal = Portal.new
    @tags = Tag.all 
  end 
  def create
    @portal = Portal.new(portal_params)
    if @portal.save 
      params[:tag][:ids].each do |tag_id, checked|
        if checked == "1"
          @tagging = Tagging.new(portal_id: @portal.id, tag_id: tag_id)
          @tagging.save
        end
      end 
    end
    redirect_to '/'
  end

  def destroy
    @portal = Portal.find(params[:id])

    @portal.destroy

    redirect_to '/'
  end
  def update
    @portal = Portal.find(params[:id])
    if @portal.update(portal_params)
      @taggings = @portal.taggings
      @taggings.destroy_all
        params[:tags][:ids].each do |tag_id, checked|
          if checked == "1"
            @taggings = Tagging.new(portal_id: @portal.id, tag_id: tag_id)
            @taggings.save
          end
        end
      redirect_to @portal
    else
      render 'edit'
    end
  end
  def edit
    @portal = Portal.find(params[:id])
    @tags = Tag.all 
  end 
  private
    def portal_params
      params.require(:portal).permit(:title, :description, :user_id, :category_id, :origin_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :character_name, :character_description, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController

	def create
    	portal = Portal.find(params[:taggings][:portal_id])
		@tagging = Tagging.new(params.require(:tagging).permit(:portal_id))
		@tagging.user_id = current_user.id
		@tagging.save
	end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,800|Oswald:400,600" rel="stylesheet">
    
    <title>The Veldt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
      <% if current_user %>
              <li><%= link_to image_tag("return.png"), :back, :class=>"return icons" %></li>

     <li><%= link_to image_tag("home.png"), "/", :class=>"icons"%></li>
        <li><%= link_to image_tag("user.png"), "/users/#{current_user.id}", :class=>"icons"%></li>
        <li><%= link_to image_tag("003-new-file.png"), new_portal_path, :class=>"icons" %></li>
        <li><%= link_to(image_tag('logout.png'), destroy_user_session_path, method: :delete) %></li>        

      <% end %>
      </ul>
    </nav>
    <div class="page-wrapper">
  	  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
  </body>
</html>

<!-- 

Filter by Categories / Author, Sort By Date
Snaps / Claps (Like Medium but I thought of it first)
Link to Public Profile Page 
Private Game Notes 
Prompt above
Alert when new comments 

Style Edit Profile 
Style Profile

 -->

app/views/portals/edit.html.erb
<h1 style="text-align: center;">Edit Your Post</h1>
 
<%= form_for @portal do |form| %>
    <p>
    <%= form.text_field :title, :class =>"update_title", :placeholder =>"Title - e.g. Dr Cumberbunds Great Adventure" %>
  </p>

  <p>
    <%= form.text_area :description, :class => "tinymce" %>
  </p>
  <div class="tags">
    <%= form.label :tags %>:<br>
  <% @tags.each do |tag| %>
    <%= check_box('tags[ids]', tag.id, {checked: tag.assigned(@portal)}) %>
    - <%= form.label tag.name %><br>
  <% end %>
  </div>
    <%= form.hidden_field :origin_id, :value => params[:origin] %>
    <%= form.hidden_field :user_id, :value => current_user.id %>

    <%= form.submit 'Submit' , :class => 'portal_submit'%>



 

  <% end %>
 


<%= tinymce %>

<style>
iframe { height: 300px !important; }
</style>

app/views/portals/index.html.erb
<div style="margin: 0 auto;width:100%;">
		<ul class="origin">

<% @portals.sort_by(&:created_at).reverse.each do |portal| %>
		<ul class="">
			<li><h2><%= link_to portal.title, portal_path(portal) %></h2></li>
			<li class="tags">
				<% portal.tags.each do |tag|%>
					<div class="tag_display <%= tag.name %>"></div>
				<% end %> 
			</li>
			<li class="author">
				created by 
				<% if portal.user.character_name %>
				<%= portal.user.character_name %>
				<% else %>
				<%= portal.user.first_name %>
				<% end %>	
				on <%= portal.created_at.strftime('%D')
 %>
				</li>
			<% if portal.user.id == current_user.id %>
				<li class="user_links"><%= link_to "edit", edit_portal_path(portal) %> - <%= link_to 'delete', 
             portal_path(portal), 
                         method: :delete, 
                         data: { confirm: 'are you sure?' } %></li>

			<% end %>

		</ul>
<% end %>
</ul>
</div>

<style>
	ul  ul { 
	 	list-style: none;
	 	padding: 0px;
	 	margin: 5px;
	 	box-sizing: border-box;
	 	word-wrap: break-word;
	 	vertical-align: top;
	 }

	 h2 a{ text-decoration: none }

	 .origin { padding-left: 0; }

	 .author { font-size: 9pt; }
	 .user_links { margin-top: 10px; }
</style>

app/views/portals/new.html.erb
<%= form_for @portal do |form| %>
  <p>
    <%= form.text_field :title, :class =>"update_title", :placeholder =>"Title - e.g. Dr Cumberbunds Great Adventure" %>
  </p>

  <p>
    <%= form.text_area :description, :class => "tinymce" %>
  </p>
  <div class="tags">
  <%= form.label :tags %>:<br>
  <% @tags.each do |tag| %>
    <%= check_box('tag[ids]', tag.id) %>
      <%= form.label tag.name %><br>
  <% end %>
  </div>
    <%= form.hidden_field :origin_id, :value => params[:origin] %>
    <%= form.hidden_field :user_id, :value => current_user.id %>

    <%= form.submit 'Submit' , :class => 'portal_submit'%>
<% end %>
<%= tinymce %>

<style>
iframe { height: 300px !important; }
</style>

app/views/portals/show.html.erb
<h1><%= @portal.title %></h1>
<% if @portal.user.id == current_user.id %>
	<p><%= link_to "edit", edit_portal_path(@portal) %> </p>
<% end %>
<h5><%= @portal.user.character_name %> <br>
  <span style="font-weight:normal"><%= @portal.created_at.strftime('%D') %></span></h5>
<p><%= @portal.description.html_safe %></p>


<div class="out_of_character">
  <%= form_for([@portal, @portal.comments.build]) do |f| %>
    <p>
 <%= f.text_area :body, :class => "comment", placeholder: "out of character comments" %>    </p>
    <p>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :in_character, :value => false %>
      <%= f.submit "Comment", :id => "save-button" %>
    </p>
  <% end %>
  <% @portal.comments.each do |comment| %>
    <% if comment.in_character == false %>
    <p class="comment-wrapper">
      <span style="font-weight: bolder">
      <% if comment.user.character_name %>
        <%= comment.user.character_name %>
      <% else %>
        <%= comment.user.first_name %>
      <% end %>
    </span>
      : <%= comment.body %>
    <span class="delete-comment">
    <% if comment.user == current_user %>
    <%= link_to 'X', 
                         portal_comment_url(@portal, comment), 
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %> 
    <% end %> 
    </span>
    <% end %>
  <% end %>


</div>

<div class="in_character">
  <%= form_for([@portal, @portal.comments.build]) do |f| %>
    <p>
      <%= f.text_area :body, :class => "comment", placeholder: "in character comments" %>
    </p>
    <p>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :in_character, :value => true %>
      <%= f.submit "Comment", :id => "save-button" %>
    </p>
  <% end %>
  <% @portal.comments.each do |comment| %>
    <% if comment.in_character == true %>
      <p class="comment-wrapper">
      <span style="font-weight: bolder">
      <% if comment.user.character_name %>
        <%= comment.user.character_name %>
      <% else %>
        <%= comment.user.first_name %>'s Character
      <% end %>
    </span>
      : <%= comment.body %>
    <span class="delete-comment">
    <% if comment.user == current_user %>
    <%= link_to 'X', 
                         portal_comment_url(@portal, comment), 
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %> 
    <% end %> 
    </span>
    <% end %>
  <% end %>

</div>

app/views/users/show.html.erb
<% if @user == current_user %>
<div class="edit-nav">
<%= link_to 'edit profile', edit_user_registration_path %>
</div>
<div class="profile-content">

<section class="notes-drawer">
	<p><em>only you can see this*</em></p>
	<textarea>
		
	</textarea>
</section>
<% end %>
 
<section class="character_name">
<h1 style="margin-top: 0;"><%= @user.character_name %></h1> <br>
<p><%= @user.character_description %></p><br>
</section>
</div>

<% if @user.avatar %>
<% @user.avatar.each do | avatar | %>
	<%= avatar %>
<% end %>
<% end %>
<!-- remaining hp -->
<!-- dice roller slide in -->
<!-- notes slide in -->
<!-- notes persist -->
<style>
@media only screen and (min-width: 801px) {	
	.notes-drawer textarea{ 
    padding: 20px;
    height: 80vh;
    width: 200px;
    margin: 0 auto;
	}

	.notes-drawer { width: 200px; }

	.character_name {
		width: 350px;
		margin-left: 40px;
	}
	.profile-content {
		margin-top: 20px;
	}
}

.notes-drawer p { text-align: center; font-size: 8pt; }
.notes-drawer, .character { 
	display: inline-block;
	vertical-align: top;

}

.notes-drawer textarea {
	    box-sizing: border-box;
    font-size: 12pt;
    border: 2px solid black;
}


.edit-nav { float: right; }

</style>